### ISSUE TITLE
[BUG] Cursor is not displayed if process is exited without calling .stop()

### ISSUE THREAD

**Issue by SteelAlloy** [denosaurs/wait#2]
On Linux when pressing `ctrl+c` to stop the process, the cursor will not be restored.

**Comment by notfilippo** [comment]
This is due to deno not having clear support for signals at this time. We can listen for a quit event but it does not always fire and it's not cross platform

**Comment by eliassjogreen** [comment]
Yep, the deno signals don't currently support windows
