### ISSUE TITLE
[BUG] Gittering cursor on Windows

### ISSUE THREAD

**Issue by SteelAlloy** [denosaurs/wait#3]
The cursor is not hidden on Windows, so the spinner is not very attractive.
![wait](https://user-images.githubusercontent.com/52361520/93688321-3d2bbf80-fac5-11ea-9596-fbf8d06d499b.gif)

**Comment by eliassjogreen** [comment]
I don't think hiding the cursor is possible on windows (but am not sure). This could also be a problem with certain terminals.

**Comment by SteelAlloy** [comment]
Hiding the cursor under Windows is possible (check cliffy dynamic prompts).

**Comment by eliassjogreen** [comment]
Note to self to hide: `\x1B[?25l` and to show: `\x1B[?25h`

**Comment by eliassjogreen** [comment]
Actually it seems to not be enabled for windows for some reason ([mod.ts:157](https://github.com/denosaurs/wait/blob/master/mod.ts#L157)). Ping @qu4k considering you wrote this and tty originally?

**Comment by notfilippo** [comment]
The windows limitation was already present in the original implementation (ora by sindre).


I don't have the means to test if this actually was a mistake and the feature is supported by windows natively. @oganexon If you find that's the case can you please open a pull?
