### ISSUE TITLE
Not loading spinner

### ISSUE THREAD

**Issue by denyncrawford** [denosaurs/wait#6]
It doesn't load any spinner when I specify it, it only loads the line spinner:

My example:

```javascript
const spinner = wait({
  text: "Iniciando servidor en el puerto 3000",
  spinner: "dots2"
}).start();

await delay(2000)

spinner.text = "Espera mientras se genera la url del servidor...";
```
Or using the spinner object:

```javascript
const spinner = wait({
  text: "Iniciando servidor en el puerto 3000",
  spinner: {
    interval: 80,
    frames: ["⣾", "⣽", "⣻", "⢿", "⡿", "⣟", "⣯", "⣷"],
  }
}).start();

...
```

This is what I get:

![image](https://user-images.githubusercontent.com/28849055/106299855-7c68da80-6234-11eb-9ed2-5354dc8dd807.png)

When I do a log of my Spinner.spinner: `{ interval: 130, frames: [ "-", "\\", "|", "/" ] }`

**Comment by eliassjogreen** [comment]
Fixed by `0.1.10`, requires `[Console]::OutputEncoding = [Text.UTF8Encoding]::UTF8` to be run on windows for all utf-8 character spinners to work correctly
