### ISSUE TITLE
Problem after running an executable compiled file: `error: TypeError: mod5.stripAnsi is not a function`

### ISSUE THREAD

**Issue by xeho91** [denosaurs/wait#7]
Hi!

Thanks for this great utility. It is neat to use.

## The problem

After running an executable file, straight after using a command  `deno compile`. I am getting an error: 
```
error: TypeError: mod5.stripAnsi is not a function
    at Spinner.updateLines (file://$deno$/bundle.js:8079:33)
    at Spinner.set text (file://$deno$/bundle.js:8022:14)
    at new Spinner (file://$deno$/bundle.js:7984:19)
    at wait (file://$deno$/bundle.js:7957:12)
    at task (file://$deno$/bundle.js:8129:21)
    at loadColorsConfig (file://$deno$/bundle.js:10458:11)
    at file://$deno$/bundle.js:10482:7
```
I am lost on how to solve it by myself. Therefore I ask for guidance.
There was no problem or any error while using the command  `deno run ...`.

Just in case I have disabled the snippet where I am using your spinner, it works _(my own CLI program)_, so I can rule out that the problem isn't with my code.

## Additional info:

- **wait**: v.0.1.10
- **Deno**: v1.10.2
- **OS**: Manjaro Linux x86_64
- **Shell**: zsh 5.8

**Comment by eliassjogreen** [comment]
This is most likely a problem with the SWC bundler of deno and does not have anything to do with `wait`. I will try updating our deps in case thats the problem but if not you will simply have to wait. Look for issues in the main deno repo which may be related (keywords could be: swc, bundle, compile, compiling dependencies)
