### ISSUE TITLE
Property 'consoleSize' does not exist on type 'typeof Deno'

### ISSUE THREAD

**Issue by tscpp** [denosaurs/wait#8]
The package depends on that the '--unstable' flag is enabled. I do not want to enable unstable APIs and until 'Deno.consoleSize' is a stable API the consoleSize should be optional. I think a "try-catch" statement is enough for supporting stable versions.

```
error: TS2339 [ERROR]: Property 'consoleSize' does not exist on type 'typeof Deno'. 'Deno.consoleSize' is an unstable API. Did you forget to run with the '--unstable' flag?
    const columns = Deno.consoleSize(this.#stream.rid)?.columns || 80;

    at https://deno.land/x/wait@0.1.11/mod.ts:208:26
```

**Comment by eliassjogreen** [comment]
I will get to it once i get home from vacation.

**Comment by eliassjogreen** [comment]
Unless you would like to create a pull request implementing such a feature which would be much appreciated!
